language: node_js
  - 14
dist: xenial
services:
  - xvfb
notifications:
  email: false
node_js:
  - "node"
script:
  - xvfb-run -a npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
